language: ruby
cache: bundler
branches:
  only:
  - master
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination _site
deploy:
  provider: pages
  local-dir: ./_site
  target-branch: gh-pages
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip_cleanup: true
  cleanup: false
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
