title: Obscuriosities
# This subtitle will be part of the title in podcast apps, after a colon.
subtitle: The Depths of Video Game History
frontpage-blurb-heading: Do you believe in the value of the unknown?
frontpage-blurb: <em>Obscuriosities</em> is a journey through the farthest reaches of video game history with Japanese translator Samuel “Obskyr” Messner.
description: >-
  The podcast about obscure video games. Journey to the farthest reaches of video game history – well-kept Japanese-only secrets, forgotten retro games, and everything in between – with Japanese translator and video game preservationist Samuel “Obskyr” Messner. Do you believe in the value of the unknown?
theme-color: '#191F42'
permalink: ':title/'
url: "https://podcast.obskyr.io" # Don't include the base path here!
baseurl: "" # The subpath of your site, e.g. "/blog".
copyright-start-year: 2020
site-twitter: # If the website itself has a Twitter account.
site-source-link: https://github.com/obskyr/obscuriosities

# Author settings
author: Obskyr
author-img: logo/logo.png
card-image: logo/card.png
about-author:
social-twitter: obskyr
social-facebook:
# social-github: obskyr/obscuriosities
social-linkedin:
social-email: obskyr@obskyr.io

# jekyll-tagging settings.
tag_page_layout: tag_post_list
tag_page_dir: tags

# Octopod settings. Why couldn't they have placed this in an object...
author_url: "https://obskyr.io/"
email: obskyr@obskyr.io
itunes_url: https://podcasts.apple.com/podcast/obscuriosities/id1513125957
spotify_url: https://open.spotify.com/show/79sk8ST8WysPrY2ccJfrcs
# At the time of writing:
# • YouTube Music's podcast feature is only available in the USA(???).
# • YouTube Music does not support podcasts via RSS feeds (yet?).
# • I'm miffed that Google discontinued Google Podcasts. It didn't capture
#   enough market share? Might that perhaps have something to do with the
#   complete lack of marketing and feature updates!? (╯ °□°) ╯
# So I don't think I'll include the following at the present moment.
# youtube_music_url: 
pocket_casts_url: https://pca.st/cid4glzr
keywords: ['video games', games, technology, obscure]
itunes_categories: [['Leisure', 'Video Games'], Technology, Education]
language: en
explicit: no
episodes_per_feed_page: 100

use_podtrac: yes

player_theme: obscuriosities
date_format: ordinal

## If rsync deployments via Octopod are ever to be done:
# ssh_host: user@host.org
# ssh_port: 22
# document_root: /path/to/your/htdocs/
# rsync_delete: true

## Feed links; optional
# itunes_url: https://itunes.apple.com/at/podcast/myname/id232323
# google_play_url: https://playmusic.app.goo.gl/...
# bitlove_url: https://bitlove.org/myaccount
# fyyd_url: https://fyyd.de/podcast/myaccount/myid
# gpodder_url: https://gpodder.net/podcast/mypodcast

# To add comments, set a Disqus identifier.
# disqus-identifier:
# Or use Isso.
# isso-url: https://comments.podcast.obskyr.io

# Google Analytics
# analytics:

# Build settings
markdown: kramdown
plugins:
  - jekyll-octopod
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll/tagging
  - jekyll-postfiles

paginate: 8
paginate_path: "/page/:num"

exclude:
  - /jekyll-octopod
  - /octopod
  - /processnotionmd.py
  - /optimizeimages.sh
  - /LICENSE
  - _drafts/template.md
  # Workaround for a jekyll-postfiles bug. https://github.com/nhoizey/jekyll-postfiles/issues/1
  - _drafts/**/*.jpg
  - _drafts/**/*.jpeg
  - _drafts/**/*.png
  - _drafts/**/*.webp
  - _posts/**/*.jpg
  - _posts/**/*.jpeg
  - _posts/**/*.png
  - _posts/**/*.webp

sass:
  sass_dir: assets/css/_sass

# Not actually, but to make per-post timezones actually somewhat work...
timezone: UTC
# Needed in order to be able to publish posts in the early morning of a
# time zone ahead of UTC. :|
future: true
